"""Build identity, generated by build.ps1 rather than inferred at runtime."""
from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path


def version_tuple(value: str) -> tuple[int, int, int]:
    if not re.fullmatch(r"v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)", value):
        raise ValueError("Invalid stable version")
    return tuple(int(part) for part in value.removeprefix("v").split("."))


@dataclass(frozen=True)
class BuildInfo:
    version: str = "development"
    build_type: str = "development"
    commit: str = "unknown"

    @property
    def update_enabled(self) -> bool:
        return bool(getattr(sys, "frozen", False)) and self.build_type == "stable" and sys.platform == "win32"


def read_build_info(path: Path | None = None) -> BuildInfo:
    if path is None:
        if not getattr(sys, "frozen", False):
            return BuildInfo()
        path = Path(sys._MEIPASS) / "build-info.json"
    try:
        raw = json.loads(path.read_text(encoding="utf-8-sig"))
        info = BuildInfo(raw["version"], raw["build_type"], raw["commit"])
        if info.build_type not in {"stable", "development"}:
            raise ValueError("Invalid build type")
        if not all(isinstance(value, str) for value in (info.version, info.commit)):
            raise ValueError("Invalid build identity")
        if info.build_type == "stable":
            version_tuple(info.version)
        return info
    except (OSError, ValueError, KeyError, TypeError):
        return BuildInfo()
