from __future__ import annotations

import os
import re
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from database.models import Mango
from openvpn.addressing import ValidationError


DEFAULT_SERVER_HOST = "<VPN_SERVER_HOST>"
_PEM_LIMIT = 1024 * 1024
_PRIVATE_BLOCK = re.compile(
    r"-----BEGIN (?:ENCRYPTED )?PRIVATE KEY-----.*?"
    r"-----END (?:ENCRYPTED )?PRIVATE KEY-----",
    re.DOTALL,
)
_STATIC_KEY_BLOCK = re.compile(
    r"-----BEGIN OpenVPN Static key V1-----.*?"
    r"-----END OpenVPN Static key V1-----",
    re.DOTALL,
)


@dataclass(frozen=True, slots=True)
class ExportBundle:
    files: dict[str, str]
    mango_ids: tuple[int, ...]
    complete_mango_ids: tuple[int, ...] = ()
    warnings: tuple[str, ...] = ()
    contains_private_keys: bool = False
    ready_for_export: bool = False


def _ccd(mango: Mango) -> str:
    network, prefix = mango.lan_network.split("/")
    if prefix != "24":
        raise ValidationError("Only /24 Mango LAN networks are supported.")
    return (
        f"ifconfig-push {mango.vpn_ip} 255.255.0.0\n"
        f"iroute {network} 255.255.255.0\n"
    )


def _validate_server_host(host: str) -> str:
    host = host.strip()
    if not host or host == DEFAULT_SERVER_HOST:
        return DEFAULT_SERVER_HOST
    if len(host) > 253 or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9.:-]*", host):
        raise ValidationError("The VPN server address contains unsupported characters.")
    return host


def _read_pem(path: Path, pattern: str) -> str | None:
    try:
        if not path.is_file() or path.stat().st_size > _PEM_LIMIT:
            return None
        content = path.read_text(encoding="utf-8", errors="strict")
    except (OSError, UnicodeError):
        return None
    match = re.search(pattern, content, re.DOTALL)
    return match.group(0).strip() if match else None


def _certificate(path: Path) -> str | None:
    return _read_pem(
        path,
        r"-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----",
    )


def _private_key(path: Path) -> str | None:
    return _read_pem(
        path,
        r"-----BEGIN (?:ENCRYPTED )?PRIVATE KEY-----.*?"
        r"-----END (?:ENCRYPTED )?PRIVATE KEY-----",
    )


def _tls_key(pki_path: Path) -> tuple[Path | None, str | None]:
    for name in ("ta.key", "tls-crypt.key"):
        path = pki_path / name
        material = _read_pem(
            path,
            r"-----BEGIN OpenVPN Static key V1-----.*?"
            r"-----END OpenVPN Static key V1-----",
        )
        if material:
            return path, material
    return None, None


def _client_config(
    mango: Mango,
    server_host: str,
    server_port: int,
    ca_certificate: str,
    client_certificate: str,
    client_key: str,
    tls_key: str | None,
) -> str:
    tls_section = ""
    if tls_key:
        tls_section = f"""
<tls-crypt>
{tls_key}
</tls-crypt>
"""
    return f"""# Generated by Mango VPN Manager for {mango.name}
client
dev tun
proto udp
remote {server_host} {server_port}
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
data-ciphers AES-256-GCM:AES-128-GCM
data-ciphers-fallback AES-256-GCM
auth SHA256
verb 3

<ca>
{ca_certificate}
</ca>

<cert>
{client_certificate}
</cert>

<key>
{client_key}
</key>
{tls_section}"""


def _windows_path(path: Path) -> str:
    windows_path = str(path).replace("/", "\\")
    return windows_path.replace("\\", "\\\\")


def _server_config(
    mangos: list[Mango],
    server_port: int,
    openvpn_config_dir: Path,
    status_path: Path,
    pki_path: Path,
    tls_key_path: Path | None,
) -> str:
    routes = "\n".join(
        f"route {mango.lan_network.split('/')[0]} 255.255.255.0"
        for mango in sorted(mangos, key=lambda item: item.name.casefold())
    )
    tls_line = (
        f'tls-crypt "{_windows_path(tls_key_path)}"\n'
        if tls_key_path is not None
        else ""
    )
    return f"""# Generated by Mango VPN Manager
port {server_port}
proto udp
dev tun

topology subnet
server 10.8.0.0 255.255.0.0
client-config-dir "{_windows_path(openvpn_config_dir / "ccd")}"

{routes}

keepalive 10 120
persist-key
persist-tun

data-ciphers AES-256-GCM:AES-128-GCM
data-ciphers-fallback AES-256-GCM
auth SHA256
verify-client-cert require
dh none
{tls_line}
ca "{_windows_path(pki_path / "ca.crt")}"
cert "{_windows_path(pki_path / "issued" / "server.crt")}"
key "{_windows_path(pki_path / "private" / "server.key")}"

status "{_windows_path(status_path)}" 5
status-version 3
verb 3
"""


def build_export_bundle(
    mangos: list[Mango],
    *,
    pki_path: Path | None = None,
    server_host: str = DEFAULT_SERVER_HOST,
    server_port: int = 1194,
    openvpn_config_dir: Path | None = None,
    openvpn_status_path: Path | None = None,
) -> ExportBundle:
    if not mangos:
        raise ValidationError("No Mangos were selected for export.")
    server_host = _validate_server_host(server_host)
    if not 1 <= server_port <= 65535:
        raise ValidationError("The VPN server port must be between 1 and 65535.")

    pki = Path(pki_path) if pki_path is not None else Path("__missing_pki__")
    config_dir = (
        Path(openvpn_config_dir)
        if openvpn_config_dir is not None
        else Path(r"C:\Program Files\OpenVPN\config")
    )
    status_path = (
        Path(openvpn_status_path)
        if openvpn_status_path is not None
        else config_dir / "server-status.log"
    )
    ca = _certificate(pki / "ca.crt")
    tls_path, tls = _tls_key(pki)
    server_certificate = _certificate(pki / "issued" / "server.crt")
    server_key = _private_key(pki / "private" / "server.key")

    warnings: list[str] = []
    if server_host == DEFAULT_SERVER_HOST:
        warnings.append("VPN server address is still a placeholder.")
    if not ca:
        warnings.append("CA certificate is missing.")
    if not server_certificate or not server_key:
        warnings.append("Server certificate or server private key is missing.")
    if not tls:
        warnings.append("Optional TLS-crypt key is missing; TLS-crypt is omitted.")

    files: dict[str, str] = {}
    complete_ids: list[int] = []
    contains_private_keys = False
    for mango in sorted(mangos, key=lambda item: item.name.casefold()):
        client_certificate = _certificate(pki / "issued" / f"{mango.name}.crt")
        client_key = _private_key(pki / "private" / f"{mango.name}.key")
        if not client_certificate or not client_key:
            warnings.append(f"Certificate or private key is missing for {mango.name}.")
        effective_ca = ca or "<CA_CERTIFICATE_MISSING>"
        effective_certificate = (
            client_certificate or f"<CLIENT_CERTIFICATE_MISSING:{mango.name}>"
        )
        effective_key = client_key or f"<CLIENT_PRIVATE_KEY_MISSING:{mango.name}>"
        files[f"ccd/{mango.name}"] = _ccd(mango)
        files[f"clients/{mango.name}.ovpn"] = _client_config(
            mango,
            server_host,
            server_port,
            effective_ca,
            effective_certificate,
            effective_key,
            tls,
        )
        if client_key:
            contains_private_keys = True
        if (
            mango.id is not None
            and server_host != DEFAULT_SERVER_HOST
            and ca
            and client_certificate
            and client_key
        ):
            complete_ids.append(mango.id)

    files["server.ovpn"] = _server_config(
        mangos,
        server_port,
        config_dir,
        status_path,
        pki,
        tls_path,
    )
    route_lines = [
        "# Generated route list for review.",
        *(
            f"route {mango.lan_network.split('/')[0]} 255.255.255.0"
            for mango in sorted(mangos, key=lambda item: item.name.casefold())
        ),
    ]
    files["server_routes.conf"] = "\n".join(route_lines) + "\n"

    readme_lines = [
        "Mango VPN Manager export",
        "",
        "Copy server.ovpn and the ccd directory to:",
        str(config_dir),
        "",
        "Client configurations are stored in clients.",
        "Protect this export because client configurations may contain private keys.",
    ]
    if warnings:
        readme_lines.extend(("", "Warnings:", *(f"- {item}" for item in warnings)))
    files["EXPORT_README.txt"] = "\n".join(readme_lines) + "\n"

    return ExportBundle(
        files=files,
        mango_ids=tuple(m.id for m in mangos if m.id is not None),
        complete_mango_ids=tuple(complete_ids),
        warnings=tuple(warnings),
        contains_private_keys=contains_private_keys,
        ready_for_export=(
            server_host != DEFAULT_SERVER_HOST
            and bool(ca)
            and bool(server_certificate)
            and bool(server_key)
            and len(complete_ids) == len(mangos)
        ),
    )


def redact_sensitive_material(content: str) -> str:
    content = _PRIVATE_BLOCK.sub("[PRIVATE KEY HIDDEN IN PREVIEW]", content)
    return _STATIC_KEY_BLOCK.sub("[TLS KEY HIDDEN IN PREVIEW]", content)


def render_preview(bundle: ExportBundle) -> str:
    sections: list[str] = []
    for relative_path, content in sorted(bundle.files.items()):
        sections.extend(
            (
                f"===== {relative_path} =====",
                redact_sensitive_material(content).rstrip(),
                "",
            )
        )
    return "\n".join(sections)


def _validate_relative_path(relative_path: str) -> None:
    path = PurePosixPath(relative_path)
    if path.is_absolute() or ".." in path.parts:
        raise ValidationError(f"Unsafe export path: {relative_path}")


def validate_export_directory(directory: Path) -> Path:
    resolved = directory.expanduser().resolve()
    normalized = str(resolved).replace("/", "\\").casefold().rstrip("\\")
    protected_markers = (
        "\\program files\\openvpn",
        "\\program files (x86)\\openvpn",
    )
    if any(
        normalized.endswith(marker) or f"{marker}\\" in f"{normalized}\\"
        for marker in protected_markers
    ):
        raise ValidationError(
            "Exporting into an OpenVPN installation directory is disabled."
        )
    return resolved


def existing_export_files(bundle: ExportBundle, directory: Path) -> list[Path]:
    directory = validate_export_directory(directory)
    return [directory / path for path in bundle.files if (directory / path).exists()]


def write_export(
    bundle: ExportBundle,
    directory: Path,
    overwrite: bool = False,
) -> list[Path]:
    directory = validate_export_directory(directory)
    for relative_path in bundle.files:
        _validate_relative_path(relative_path)
    collisions = existing_export_files(bundle, directory)
    if collisions and not overwrite:
        raise FileExistsError("Export files already exist.")

    directory.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=".mango-export-", dir=directory))
    backup = staging / ".backup"
    written: list[Path] = []
    replaced: list[tuple[Path, Path]] = []
    try:
        for relative_path, content in bundle.files.items():
            staged_file = staging / relative_path
            staged_file.parent.mkdir(parents=True, exist_ok=True)
            staged_file.write_text(content, encoding="utf-8", newline="\n")

        for relative_path in bundle.files:
            target = directory / relative_path
            target.parent.mkdir(parents=True, exist_ok=True)
            if target.exists():
                backup_file = backup / relative_path
                backup_file.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(target, backup_file)
                replaced.append((target, backup_file))
            os.replace(staging / relative_path, target)
            written.append(target)
    except Exception:
        for target in reversed(written):
            backup_file = backup / target.relative_to(directory)
            if backup_file.exists():
                os.replace(backup_file, target)
            elif target.exists():
                target.unlink()
        raise
    finally:
        shutil.rmtree(staging, ignore_errors=True)
    return written
